version: '3'
services:
  ryr-api-db:
    image: postgres:9.6.1
    networks:
      - ryr
  ryr-api-nginx:
    build: docker/nginx
    depends_on:
      - ryr-api-django
    ports:
      - "10080:80"
    networks:
      - ryr
  ryr-api-redis:
    image: redis:3.2.9
    networks:
      - ryr
  ryr-api-rabbitmq:
    image: rabbitmq:3.6.10-management
    ports:
      - "15672:15672"
    networks:
      - ryr
  ryr-api-django:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash /django-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "18000:8000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@ryr-api-db:5432/postgres
      REDIS_URL: redis://ryr-api-redis:6379
    env_file:
      - docker/env-files/celery.env
    depends_on:
      - ryr-api-db
      - ryr-api-redis
    networks:
      - ryr
  ryr-api-celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash /celery-entrypoint.sh beat
    depends_on:
      - ryr-api-django
      - ryr-api-rabbitmq
    volumes:
      - .:/code
    env_file:
      - docker/env-files/celery.env
    networks:
      - ryr
  ryr-api-celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash /celery-entrypoint.sh worker
    depends_on:
      - ryr-api-django
      - ryr-api-rabbitmq
    volumes:
      - .:/code
    env_file:
      - docker/env-files/celery.env
    networks:
      - ryr
  ryr-api-celery_flower:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash /celery-entrypoint.sh flower
    depends_on:
      - ryr-api-django
      - ryr-api-rabbitmq
    ports:
      - "15555:5555"
    volumes:
      - .:/code
    env_file:
      - docker/env-files/celery.env
    networks:
      - ryr

networks:
  ryr:
    external: true
